### ISSUE TITLE
AttributeError: module 'math' has no attribute 'np'

### ISSUE THREAD

**Issue by thima2017** [Niuskir/Electron-Orbitals-Blender-3D#1]
I don't know what to do with that. I use Blender 2.79b that is default version in Lubuntu 18.04. All python3 stuff is from Lubuntu 18.04 defaults too.

The console output: 

Read blend: /home/user/Documents/Работы/Landing/CosmicDust/atom/Electron-Orbitals-Blender-3D-master/Electron_Orbitals v4.blend
path not found 
numpy version:   1.13.3
sympy version:   1.3
Python version: 2.79 (sub 0)
Traceback (most recent call last):
  File "/home/user/Documents/Работы/Landing/CosmicDust/atom/Electron-Orbitals-Blender-3D-master/Electron_Orbitals v4.blend/Electron_Orbitals_v4.py", line 678, in <module>
  File "/home/user/Documents/Работы/Landing/CosmicDust/atom/Electron-Orbitals-Blender-3D-master/Electron_Orbitals v4.blend/Electron_Orbitals_v4.py", line 623, in display_orbital
  File "/home/user/Documents/Работы/Landing/CosmicDust/atom/Electron-Orbitals-Blender-3D-master/Electron_Orbitals v4.blend/Electron_Orbitals_v4.py", line 102, in main
  File "/home/user/Documents/Работы/Landing/CosmicDust/atom/Electron-Orbitals-Blender-3D-master/Electron_Orbitals v4.blend/Electron_Orbitals_v4.py", line 526, in isosurface
  File "/home/user/Documents/Работы/Landing/CosmicDust/atom/Electron-Orbitals-Blender-3D-master/Electron_Orbitals v4.blend/Electron_Orbitals_v4.py", line 526, in <listcomp>
  File "/home/user/Documents/Работы/Landing/CosmicDust/atom/Electron-Orbitals-Blender-3D-master/Electron_Orbitals v4.blend/Electron_Orbitals_v4.py", line 526, in <listcomp>
  File "/home/user/Documents/Работы/Landing/CosmicDust/atom/Electron-Orbitals-Blender-3D-master/Electron_Orbitals v4.blend/Electron_Orbitals_v4.py", line 96, in scalarfield
  File "<string>", line 1, in <lambda>
AttributeError: module 'math' has no attribute 'np'
Error: Python script fail, look in the console for now...

**Comment by Niuskir** [comment]
Hi, i have updated the script and blend file and it now supports Blender >v2.8. Please follow instructions in the Readme file re the prereqs.
